version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://server:8080/api/v1/

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./server/data:/app/data

networks:
  app-network:
    driver: bridge